

services:
  server:
    build: ./server
    container_name: server 
    ports:
      - "3001:3001"
    environment: 
      - mongodb+srv://kvaralakshmi2005:m2egOEGhlqLYIhj1@cluster0.xd8hupg.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
  client:
    build: ./client
    container_name: client
    ports :
    - "3000:80"